ibabygroup:
  swagger:
    enabled: true
    api-info:
      title: Ibaby-Member
    base-package: cn.ibabygroup.pros.member.web.controller
  net:
    host: http://192.168.1.201:30016/
  rest:
    host: http://192.168.1.203:8080/
    token: XRbghp7zHw8Yx6gX
  appconfig:
    ignore-auth: true
  duiba:
    appKey: ZP9jcASHT2WPqd5deB9E7oEAWvB
    appSecret: 2zmC21TSdwB4GoZCymVxyo8QpDHZ
spring:
  datasource:
    url: jdbc:mysql://192.168.1.222:3306/member?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
# nginx
app-uac-server-dev:
 ribbon:
  listOfServers: 192.168.1.222:9696
